org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=true
# NEVER commit real keys. Local only:
GROQ_API_KEY=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
OPENAI_API_KEY=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
